import React, { Component } from 'react';

class Metamask extends Component {

    render () {
        return (
            <div>
                <h2>MetaMask</h2>
                <p>In this module you learned the very basics of blockchain technology: what it is and how it works.</p>
                <p>Ethereum is an established public network. Some of you have already worked with Ethereum. For those of you who are new to all of this, we have put together a guide on how to connect to Ethereum for the first time and get some test Ether. Thus, you will be able to gather some experience with this network. Later on, you will receive your certification on the Ethereum blockchain.</p>
                <p>Let's do it!</p>
                <h3>To node or not to node</h3>
                <p>To connect to a blockchain network you would usually install a client on your computer that communicates with other clients:</p>
                <ul>
                <li>to download all transactions ever made,</li>
                <li>to manage your private and public keys</li>
                <li>and to broadcast new transactions.</li>
                </ul>
                <p>Synchronising with the network takes quite a bit of time.</p>
                <p>Another, less secure but still workable, option is to use a system like MetaMask to take care of the keys, to craft transactions and to rely on another operator's node to do the rest. So we will use <a href="https://metamask.io">MetaMask</a>.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-pre-1.png" /></p>
                <p>MetaMask is a Chrome Extension that allows you to interact with the Ethereum network without having to run a node on your system. There are advantages and disadvantages to this approach but it is great for our purpose here.</p>
                <p>So, head to <a href="https://metamask.io">metamask.io</a>. Enjoy the fox animation for a second. Now click "Get Chrome Plugin".</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-pre-2.png" /></p>
                <p>Install the Chrome plugin. This adds a little fox icon to your extension bar. Click on the icon and follow instructions to accept disclaimer and terms &amp; conditions.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-1.png" />
                <img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-2.png" /></p>
                <p className="b9-info">
                Just like the fox is following your every mouse moves, MetaMask's plugin is following your every Ethereum moves.
                </p>
                <h3>Choose the network</h3>
                <p>In the next step you are choosing a node to connect to. Depending on what network the node is connected to you will interact with the Ethereum Mainnet, one of the testnets or your own configuration.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-3.png" /></p>
                <p>When you click on the top left "Ethereum Main Net" button of the MetaMask window you will see the selection above. For our purposes please select <strong>Ropsten Test Network</strong>.</p>
                <p>Now MetaMask will connect to a public node that is part of the Ethereum Ropsten testnet.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-4.png" /></p>
                <p>Enter a new password to encrypt your new MetaMask vault that will hold your keys generated by MetaMask.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-5.png" /></p>
                <p className="b9-tip">
                These 12 words allow you to re-generate your keys if you ever lose them. Write this down somewhere and keep it safe. Some people call these 12 words a "brain wallet" as you only need to remember them to get access to your Ethers.
                </p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-6.png" /></p>
                <p>Right, that is the setup done. You can see your account, balance and can send transactions.</p>
                <p>But your balance of test Ether is still 0. Let's change that!</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-7.png" /></p>
                <p>B9lab is running a public faucet that gives you test Ether on the Ropsten test network for development purposes. Remember, test network Ether does not have any exchange value, it's just for testing.</p>
                <p>The faucet is served through IPFS: <a href="http://ipfs.b9lab.com:8080/ipfs/QmVAwVKys271P5EQyEfVSxm7BJDKWt42A2gHvNmxLjZMps/">http://ipfs.b9lab.com:8080/ipfs/QmVAwVKys271P5EQyEfVSxm7BJDKWt42A2gHvNmxLjZMps/</a>. If our IPFS gateway acts up, you can fall back to <a href="https://ipfs.io/ipfs/QmVAwVKys271P5EQyEfVSxm7BJDKWt42A2gHvNmxLjZMps/">https://ipfs.io/ipfs/QmVAwVKys271P5EQyEfVSxm7BJDKWt42A2gHvNmxLjZMps/</a></p>
                <p>Navigate to the faucet and the page should have already populated your address in the field next to <strong>Send To</strong>. If you have more than one address, you would need to click the small <em>copy</em> button next to your preferred address and paste it into the field yourself.</p>
                <p>If you are curious as to how it works in detail, we wrote that up <a href="https://blog.b9lab.com/when-we-first-built-our-faucet-we-deployed-it-on-the-morden-testnet-70bfbf4e317e">here</a>.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-8.png" /></p>
                <p>Next, click the <strong>Send to</strong> button. If all goes well, you should see a transaction hash. Click on it and it leads you to Etherscan where you can follow its status.</p>
                <p>If there are several of you tapping the faucet at the same time, it may refuse and you should try after 1 or 2 minutes.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-9.png" /></p>
                <p>Next, let's try something else. The faucet has a donate function where, if you have some test ether to spare you can donate to the faucet. For now let's send back 0.1 ether (or any other amount, it is up to you) to the faucet.</p>
                <p>When you click donate then the faucet page will try to send a transaction from your account to the faucet smart contract.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-10.png" /></p>
                <p>MetaMask intercepts this call and asks you whether you did intend to send a transaction. Here you can check all the details of the transaction and adjust the transaction fee. For now just press <strong>Submit</strong>.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-11.png" /></p>
                <p>Now when you click on the MetaMask icon in your extension bar you will see the pending transaction. Your balance is still 0.5 because the transaction has not been confirmed.</p>
                <p><img src="https://s3-eu-west-1.amazonaws.com/b9-academy-assets/course-assets/HLF-0/metamask-12.png" /></p>
                <p>After just a moment you will see this, the transaction has been confirmed and your balance is updated. Note that your balance is now lower by more than just 0.1. This is because you also paid a small transaction fee.</p>
                <h3>Other networks</h3>
                <p>Now you can go and connect to another network. Notice how your actions in one test network are not duplicated in another.</p>
                <p>Good luck finding a Main net faucet, though.</p>
            </div>
        )
    }

}

export default Metamask;